name: Client: Bug report 🐛
description: Something not working as expected? Create an issue to track it.
labels:
  - 'type: bug :spider:'
title: `client-bug:`
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report.
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser(s) are you experiencing the issue?
      options:
        - Chrome
        - Safari
        - Firefox
        - Edge
     validations:
      required: true
